# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "rspec", "~> 3.10"

gem "capybara", "~> 3.35"

gem "selenium-webdriver", "~> 3.142"

gem "rexml", "~> 3.2"
